server:
  port: 8203

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.xyt.ssyx.enums

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-product?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 192.160.1.180
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED  #发布确认模式，消息是否被成功发送到交换机
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual   #消费端手动确认
  redis:
    host: 192.160.1.180
    port: 6379
    database: 0
    timeout: 1800000
    password: 111111
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

aliyun:
  endpoint: xxxxxxxxxxxxxxxxx
  keyid: xxxxxxxxxxxxxxxxxxx
  keysecret: xxxxxxxxxxxxxxxxxxxxx
  bucketname: sstx-xyt
